#remote_theme: dagnelies/beautiful-jekyll
remote_theme: https://github.com/daattali/beautiful-jekyll
#remote_theme: just-the-docs/just-the-docs

title: Passwordless

author: Arnaud Dagnelies

navbar-var-length: true

navbar-links:
  F.A.Q.:
    - Is it "production ready"?: faq/TODO
    - Is it scalable?: faq/TODO
    - Why is it better than rolling your own?: faq/TODO
    - How can this be free?: faq/TODO
    - Is it secure?: faq/TODO
    - What about privacy?: faq/TODO
    - What if I loose my device?: faq/TODO
  Getting Started:
    - Javascript - Vanilla: getting_started/javascript_spa
    - Python - FastAPI: https://github.com/passwordless-id/fast-api-demo
    - Java - Spring Boot: https://github.com/passwordless-id/spring-boot-demo
    - Want more?: getting_started/want_more
  Docs:
    - The "big picture": docs/1_big_picture
    - UI screenshots: screenshots
    - OpenID configuration: usage/openid
#    - Verifying an `id_token`: usage/id_token
  Pricing: pricing
  Protocols:
    OAuth2:
      - Introduction: protocols/oauth2/1_introduction
      - /authorize: protocols/oauth2/2_authorize
      - /token: protocols/oauth2/3_token
    OpenID:
      - Introduction: TODO
      - /authorize: TODO
    Webauthn:
      - Introduction: protocols/webauthn/1_introduction
      - Registration: protocols/webauthn/2_registration
      - Authentication: protocols/webauthn/3_authentication
      - Webauthn Helper Library: usage/webauthn
      - Security & Privacy: protocols/webauthn/4_security
      - E-Mails vs Usernames: thoughts/emails-vs-usernames
      - User Guidance: thoughts/guidance
  Community:
    - Logos, icons & banners: community/logos_icons_banners
    - Discord: https://discord.gg/v73cHHnqzZ
    - Github: https://github.com/passwordless-id/www
    - Blog: https://blog.passwordless.id
    - Roadmap: https://github.com/orgs/passwordless-id/projects/1
    
#  Protocols:
#    OAuth2 / OpenID:
#      - Introduction: protocols/oauth2/1_introduction    
    


edit_page_button: true

#light: "#d4fbff"
#medium: "#6dc9f7"
#dark: "#0089ef"

navbar-col: "#0089ef"
navbar-text-col: "#fff"
navbar-border-col: "#0089ef"

page-col: "#fff"
text-col: "#000"
link-col: "#0089ef"
hover-col: "#6dc9f7"

footer-col: "#ffd7e5"
footer-text-col: "#fa759e"


#navbar-col: "#7957d5"
#navbar-text-col: "#fff"
#navbar-border-col: "#7957d5"

#page-col: "#fff"
#text-col: "#000"
#link-col: "#7957d5"
#hover-col: "#f2effb"

#footer-col: "#f2effb"
#footer-text-col: "#552fbc"
#footer-link-col: "#7957d5"
#footer-hover-col: "#000"
